service: serverless-api-app
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'local'}
  logs:
    restApi: true         # Habilita logs de API Gateway
    httpApi: true         # Si estás usando HTTP API
  environment:
    NODE_ENV: ${env:NODE_ENV}
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE, ''}
    REDIS_URL: ${env:REDIS_URL, ''}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/PlanetWeatherTable
        - Effect: Allow
          Action:
            - elasticache:*
          Resource: "*"

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node20'
    platform: 'node'

functions:
  merged:
    handler: src/presentation/lambdas/mergedHandler.main
    memorySize: 256         # Ajustado para uso eficiente (puede ser 128 si las funciones son livianas)
    timeout: 5              # Tiempo de espera en segundos (ajustado a lo necesario)
    name: get-fusionados-fn
    events:
      - http:
          path: fusionados
          method: get
          cors: true
  store:
    handler: src/presentation/lambdas/storeAggregatedHandler.main
    memorySize: 256
    timeout: 5
    name: store-aggregated-fn
    events:
      - http:
          path: almacenar
          method: post
          cors: true
  history:
    handler: src/presentation/lambdas/getHistoryHandler.main
    memorySize: 256
    timeout: 5
    name: get-history-fn
    events:
      - http:
          path: historial
          method: get
          cors: true

package:
  individually: true

resources:
  Resources:
    PlanetWeatherTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PlanetWeatherTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        
